More style fixes

diff --git a/detect_os b/detect_os
--- a/detect_os
+++ b/detect_os
@@ -65,8 +65,8 @@ install_deps()
 	    elif command -v zypper > /dev/null 2>&1; then
                 zypper install -y wget
 	    else
-		echo "Missing wget, and do not know what package manager is being used, exiting out"
-		exit 1
+                echo "Missing wget, and do not know what package manager is being used, exiting out"
+                exit 1
             fi
         fi
 
