Add error message for missing file.

diff --git a/verification b/verification
--- a/verification
+++ b/verification
@@ -37,6 +37,10 @@ verification_run()
 		ls -d * > $verify_res_after
 		popd >/dev/null
 		base_res_file=`ls $vdir/$test_base_results/*csv`
+		if [[ $? -ne 0 ]]; then
+			echo "Error, did not find a csv file in $vdir/$test_base_results"
+			continue
+		fi
 		rdir=`diff $verify_res_after $verify_res_before | grep -v tar | grep '<' |  sed "s/< //g"`
 		res_dir=${home_parent}/${run_user}/export_results/$rdir
 		new_res_file=`find $res_dir -print | grep csv | grep results | tail -1`
